"""Generate verified seed taxonomy dataset and provenance manifest."""

import json
from pathlib import Path

from careercompiler.taxonomy.models import (
    DisambiguationRule,
    EntityType,
    TaxonomyCatalog,
    TaxonomyEntity,
)

ENTITIES_DATA = [
    # ----------------------------------------------------
    # 1. Programming Languages (Source: GitHub Linguist, MIT)
    # ----------------------------------------------------
    {
        "canonical_id": "python",
        "display_name": "Python",
        "type": EntityType.LANGUAGE,
        "aliases": ["Python", "Python 3", "Python3", "python", "py"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "javascript",
        "display_name": "JavaScript",
        "type": EntityType.LANGUAGE,
        "aliases": ["JavaScript", "JS", "ES6", "ES2015", "ECMAScript", "javascript"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "typescript",
        "display_name": "TypeScript",
        "type": EntityType.LANGUAGE,
        "aliases": ["TypeScript", "TS", "typescript"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "java",
        "display_name": "Java",
        "type": EntityType.LANGUAGE,
        "aliases": ["Java", "Java 8", "Java 11", "Java 17", "Java 21", "JDK"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "c",
        "display_name": "C",
        "type": EntityType.LANGUAGE,
        "aliases": ["C", "C language", "ANSI C", "C99", "C11"],
        "ambiguous": True,
        "disambiguation_rules": [
            DisambiguationRule(
                case_sensitive=True,
                requires_context=True,
                context_keywords=["programming", "developer", "embedded", "systems", "language", "compiler", "pointer", "memory", "linux", "kernel"],
                trigger_patterns=[
                    r"\b(in|with|using)\s+C\b",
                    r"\bC\s+(programming|language|developer|engineer|code)\b",
                    r"\bC\s*[,/]\s*(C\+\+|C#|Assembly|Python|Rust|Go)",
                    r"\b(C\+\+|C#|Assembly|Python|Rust|Go)\s*[,/]\s*C\b",
                ],
                negative_patterns=[r"\b(c\s+level|c\s+suite|grade\s+c|appendix\s+c|figure\s+c|section\s+c)\b"],
            )
        ],
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "cpp",
        "display_name": "C++",
        "type": EntityType.LANGUAGE,
        "aliases": ["C++", "CPP", "Cplusplus", "C++11", "C++14", "C++17", "C++20"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "csharp",
        "display_name": "C#",
        "type": EntityType.LANGUAGE,
        "aliases": ["C#", "CSharp", "C-Sharp", "C Sharp"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "golang",
        "display_name": "Go",
        "type": EntityType.LANGUAGE,
        "aliases": ["Go", "Golang", "Go language", "golang"],
        "ambiguous": True,
        "disambiguation_rules": [
            DisambiguationRule(
                case_sensitive=True,
                requires_context=True,
                context_keywords=["programming", "developer", "engineer", "language", "code", "backend", "concurrency", "goroutine", "compiler", "runtime", "software"],
                trigger_patterns=[
                    r"\b(in|with|using|and|or)\s+Go\b",
                    r"\bGo\s+(developer|engineer|language|programming|code|backend)\b",
                    r"\bGo\s*[,/]\s*(Python|Java|Rust|C\+\+|C#)",
                    r"\b(Python|Java|Rust|C\+\+|C#)\s*[,/]\s*Go\b",
                ],
                negative_patterns=[r"\b(let's\s+go|go\s+to|go\s+ahead|go\s+for|on\s+the\s+go|give\s+it\s+a\s+go|way\s+to\s+go|where\s+to\s+go|go\s+live)\b"],
            )
        ],
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "rust",
        "display_name": "Rust",
        "type": EntityType.LANGUAGE,
        "aliases": ["Rust", "Rustlang", "Rust language"],
        "ambiguous": True,
        "disambiguation_rules": [
            DisambiguationRule(
                case_sensitive=True,
                requires_context=True,
                context_keywords=["programming", "developer", "engineer", "systems", "language", "code", "cargo", "memory-safe", "concurrency"],
                trigger_patterns=[
                    r"\b(in|with|using)\s+Rust\b",
                    r"\bRust\s+(developer|engineer|language|programming|code)\b",
                    r"\bRust\s*[,/]\s*(C\+\+|Go|Python|C)",
                    r"\b(C\+\+|Go|Python|C)\s*[,/]\s*Rust\b",
                ],
                negative_patterns=[r"\b(trust|crust|rusting|rusted|rust\s+belt|iron\s+rust)\b"],
            )
        ],
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "r",
        "display_name": "R",
        "type": EntityType.LANGUAGE,
        "aliases": ["R", "R language", "R programming", "RStudio"],
        "ambiguous": True,
        "disambiguation_rules": [
            DisambiguationRule(
                case_sensitive=True,
                requires_context=True,
                context_keywords=["programming", "statistics", "data", "analysis", "modeling", "biostatistics", "bioinformatics", "ggplot", "shiny"],
                trigger_patterns=[
                    r"\b(in|with|using)\s+R\b",
                    r"\bR\s+(programming|language|package|script|code)\b",
                    r"\bR\s*[,/]\s*(Python|SAS|SPSS|MATLAB|SQL)",
                    r"\b(Python|SAS|SPSS|MATLAB|SQL)\s*[,/]\s*R\b",
                ],
                negative_patterns=[r"\br\s*&\s*d\b", r"\br\s+and\s+d\b", r"\bgrade\s+r\b", r"\bappendix\s+r\b"],
            )
        ],
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "ruby",
        "display_name": "Ruby",
        "type": EntityType.LANGUAGE,
        "aliases": ["Ruby", "Ruby language"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "php",
        "display_name": "PHP",
        "type": EntityType.LANGUAGE,
        "aliases": ["PHP", "PHP 8", "php"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "swift",
        "display_name": "Swift",
        "type": EntityType.LANGUAGE,
        "aliases": ["Swift", "Swift language"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "kotlin",
        "display_name": "Kotlin",
        "type": EntityType.LANGUAGE,
        "aliases": ["Kotlin", "kotlin"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "scala",
        "display_name": "Scala",
        "type": EntityType.LANGUAGE,
        "aliases": ["Scala", "scala"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "julia",
        "display_name": "Julia",
        "type": EntityType.LANGUAGE,
        "aliases": ["Julia", "Julia language"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "perl",
        "display_name": "Perl",
        "type": EntityType.LANGUAGE,
        "aliases": ["Perl", "Perl 5"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "bash",
        "display_name": "Bash",
        "type": EntityType.LANGUAGE,
        "aliases": ["Bash", "Bash/Shell", "Bash scripting", "Shell script", "sh"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "powershell",
        "display_name": "PowerShell",
        "type": EntityType.LANGUAGE,
        "aliases": ["PowerShell", "pwsh"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "sql",
        "display_name": "SQL",
        "type": EntityType.LANGUAGE,
        "aliases": ["SQL", "Structured Query Language", "ANSI SQL"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "html",
        "display_name": "HTML",
        "type": EntityType.LANGUAGE,
        "aliases": ["HTML", "HTML5", "HTML 5"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "css",
        "display_name": "CSS",
        "type": EntityType.LANGUAGE,
        "aliases": ["CSS", "CSS3", "CSS 3"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "sass",
        "display_name": "Sass",
        "type": EntityType.LANGUAGE,
        "aliases": ["Sass", "SCSS"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "dart",
        "display_name": "Dart",
        "type": EntityType.LANGUAGE,
        "aliases": ["Dart", "Dart language"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "elixir",
        "display_name": "Elixir",
        "type": EntityType.LANGUAGE,
        "aliases": ["Elixir", "Elixir language"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "erlang",
        "display_name": "Erlang",
        "type": EntityType.LANGUAGE,
        "aliases": ["Erlang", "Erlang/OTP"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "haskell",
        "display_name": "Haskell",
        "type": EntityType.LANGUAGE,
        "aliases": ["Haskell", "GHC"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "lua",
        "display_name": "Lua",
        "type": EntityType.LANGUAGE,
        "aliases": ["Lua", "LuaJIT"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "clojure",
        "display_name": "Clojure",
        "type": EntityType.LANGUAGE,
        "aliases": ["Clojure", "ClojureScript"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "matlab",
        "display_name": "MATLAB",
        "type": EntityType.LANGUAGE,
        "aliases": ["MATLAB", "Matlab"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "solidity",
        "display_name": "Solidity",
        "type": EntityType.LANGUAGE,
        "aliases": ["Solidity", "sol"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "objective-c",
        "display_name": "Objective-C",
        "type": EntityType.LANGUAGE,
        "aliases": ["Objective-C", "ObjC", "Objective C"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "assembly",
        "display_name": "Assembly",
        "type": EntityType.LANGUAGE,
        "aliases": ["Assembly", "ASM", "x86", "x86-64", "ARM assembly"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },
    {
        "canonical_id": "groovy",
        "display_name": "Groovy",
        "type": EntityType.LANGUAGE,
        "aliases": ["Groovy", "Apache Groovy"],
        "ambiguous": False,
        "source": "github_linguist",
        "license": "MIT",
    },

    # ----------------------------------------------------
    # 2. Web & UI Frameworks / Libraries (Source: Stack Overflow Tag Synonyms, CC BY-SA 4.0)
    # ----------------------------------------------------
    {
        "canonical_id": "react",
        "display_name": "React",
        "type": EntityType.FRAMEWORK,
        "aliases": ["React", "React.js", "ReactJS", "React js"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "nextjs",
        "display_name": "Next.js",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Next.js", "NextJS", "Next js", "next.js"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "vue",
        "display_name": "Vue.js",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Vue.js", "Vue", "VueJS", "Vue 3", "Vue2"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "angular",
        "display_name": "Angular",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Angular", "AngularJS", "Angular 2+"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "svelte",
        "display_name": "Svelte",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Svelte", "SvelteKit"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "nuxt",
        "display_name": "Nuxt.js",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Nuxt.js", "Nuxt", "NuxtJS"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "remix",
        "display_name": "Remix",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Remix", "Remix.run"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "nodejs",
        "display_name": "Node.js",
        "type": EntityType.PLATFORM,
        "aliases": ["Node.js", "NodeJS", "Node js", "node.js"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "express",
        "display_name": "Express.js",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Express", "Express.js", "ExpressJS"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "fastapi",
        "display_name": "FastAPI",
        "type": EntityType.FRAMEWORK,
        "aliases": ["FastAPI", "fastapi"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "flask",
        "display_name": "Flask",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Flask", "flask"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "django",
        "display_name": "Django",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Django", "Django REST Framework", "DRF"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "spring-boot",
        "display_name": "Spring Boot",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Spring Boot", "SpringBoot", "Spring Framework", "Spring"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "dotnet",
        "display_name": ".NET",
        "type": EntityType.FRAMEWORK,
        "aliases": [".NET", ".NET Core", ".NET Framework", "dotnet", ".NET 6", ".NET 7", ".NET 8"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "aspnet",
        "display_name": "ASP.NET",
        "type": EntityType.FRAMEWORK,
        "aliases": ["ASP.NET", "ASP.NET Core", "ASP.NET MVC"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "gin",
        "display_name": "Gin",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Gin", "Gin-Gonic", "gin web framework"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "fiber",
        "display_name": "Fiber",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Fiber", "GoFiber", "gofiber"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "rails",
        "display_name": "Ruby on Rails",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Ruby on Rails", "Rails", "RoR"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "laravel",
        "display_name": "Laravel",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Laravel", "laravel"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "nestjs",
        "display_name": "NestJS",
        "type": EntityType.FRAMEWORK,
        "aliases": ["NestJS", "Nest.js", "nest.js"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "tailwind-css",
        "display_name": "Tailwind CSS",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Tailwind CSS", "Tailwind", "TailwindCSS"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "bootstrap",
        "display_name": "Bootstrap",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Bootstrap", "Bootstrap 5", "Bootstrap 4"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "material-ui",
        "display_name": "Material-UI",
        "type": EntityType.LIBRARY,
        "aliases": ["Material-UI", "MUI", "Material UI"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "electron",
        "display_name": "Electron",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Electron", "Electron.js"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "react-native",
        "display_name": "React Native",
        "type": EntityType.FRAMEWORK,
        "aliases": ["React Native", "ReactNative"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "flutter",
        "display_name": "Flutter",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Flutter", "flutter"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "graphql",
        "display_name": "GraphQL",
        "type": EntityType.CONCEPT,
        "aliases": ["GraphQL", "Apollo GraphQL", "graphql"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "grpc",
        "display_name": "gRPC",
        "type": EntityType.FRAMEWORK,
        "aliases": ["gRPC", "Protobuf", "Protocol Buffers", "grpc"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "rest-api",
        "display_name": "RESTful API",
        "type": EntityType.CONCEPT,
        "aliases": ["REST API", "RESTful", "RESTful API", "RESTful APIs", "REST APIs", "REST"],
        "ambiguous": True,
        "disambiguation_rules": [
            DisambiguationRule(
                case_sensitive=True,
                requires_context=True,
                context_keywords=["api", "apis", "endpoint", "endpoints", "http", "service", "services", "backend", "web", "fastapi", "openapi", "json"],
                trigger_patterns=[
                    r"\bREST(ful)?\s+(API|APIs|endpoint|endpoints|service|services|architecture|client)\b",
                    r"\b(RESTful|REST-API)\b",
                    r"\b(HTTP|API|JSON|GraphQL|gRPC|SOAP)\s*[,/]\s*REST\b",
                    r"\bREST\s*[,/]\s*(HTTP|API|JSON|GraphQL|gRPC|SOAP)\b",
                ],
                negative_patterns=[
                    r"\b(the\s+rest|rest\s+of|take\s+a\s+rest|need\s+a\s+rest|give\s+it\s+a\s+rest|at\s+rest)\b",
                ],
            )
        ],
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "websockets",
        "display_name": "WebSockets",
        "type": EntityType.CONCEPT,
        "aliases": ["WebSocket", "WebSockets", "ws"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "sse",
        "display_name": "Server-Sent Events",
        "type": EntityType.CONCEPT,
        "aliases": ["Server-Sent Events", "SSE"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },

    # ----------------------------------------------------
    # 3. Machine Learning & AI (Source: Stack Overflow & Official Documentation)
    # ----------------------------------------------------
    {
        "canonical_id": "pytorch",
        "display_name": "PyTorch",
        "type": EntityType.LIBRARY,
        "aliases": ["PyTorch", "pytorch", "torch"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "pytorch-geometric",
        "display_name": "PyTorch Geometric",
        "type": EntityType.LIBRARY,
        "aliases": ["PyTorch Geometric", "PyG", "torch_geometric"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "tensorflow",
        "display_name": "TensorFlow",
        "type": EntityType.LIBRARY,
        "aliases": ["TensorFlow", "TF", "tensorflow"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "jax",
        "display_name": "JAX",
        "type": EntityType.LIBRARY,
        "aliases": ["JAX", "jax"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "scikit-learn",
        "display_name": "Scikit-Learn",
        "type": EntityType.LIBRARY,
        "aliases": ["Scikit-learn", "scikit-learn", "sklearn"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "xgboost",
        "display_name": "XGBoost",
        "type": EntityType.LIBRARY,
        "aliases": ["XGBoost", "xgboost"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "lightgbm",
        "display_name": "LightGBM",
        "type": EntityType.LIBRARY,
        "aliases": ["LightGBM", "lightgbm"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "pandas",
        "display_name": "Pandas",
        "type": EntityType.LIBRARY,
        "aliases": ["Pandas", "pandas"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "numpy",
        "display_name": "NumPy",
        "type": EntityType.LIBRARY,
        "aliases": ["NumPy", "numpy", "np"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "scipy",
        "display_name": "SciPy",
        "type": EntityType.LIBRARY,
        "aliases": ["SciPy", "scipy"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "keras",
        "display_name": "Keras",
        "type": EntityType.LIBRARY,
        "aliases": ["Keras", "keras"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "huggingface",
        "display_name": "Hugging Face",
        "type": EntityType.PLATFORM,
        "aliases": ["Hugging Face", "HuggingFace", "HF"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "transformers",
        "display_name": "Transformers",
        "type": EntityType.LIBRARY,
        "aliases": ["Transformers", "Hugging Face Transformers", "transformers"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "opencv",
        "display_name": "OpenCV",
        "type": EntityType.LIBRARY,
        "aliases": ["OpenCV", "cv2"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "spacy",
        "display_name": "spaCy",
        "type": EntityType.LIBRARY,
        "aliases": ["spaCy", "spacy"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "nltk",
        "display_name": "NLTK",
        "type": EntityType.LIBRARY,
        "aliases": ["NLTK", "Natural Language Toolkit"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "langchain",
        "display_name": "LangChain",
        "type": EntityType.FRAMEWORK,
        "aliases": ["LangChain", "langchain"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "llamaindex",
        "display_name": "LlamaIndex",
        "type": EntityType.FRAMEWORK,
        "aliases": ["LlamaIndex", "GPT Index"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "qdrant",
        "display_name": "Qdrant",
        "type": EntityType.DATABASE,
        "aliases": ["Qdrant", "Qdrant Vector DB"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "pinecone",
        "display_name": "Pinecone",
        "type": EntityType.DATABASE,
        "aliases": ["Pinecone", "Pinecone DB"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "chromadb",
        "display_name": "ChromaDB",
        "type": EntityType.DATABASE,
        "aliases": ["Chroma", "ChromaDB"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "weaviate",
        "display_name": "Weaviate",
        "type": EntityType.DATABASE,
        "aliases": ["Weaviate", "weaviate"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "milvus",
        "display_name": "Milvus",
        "type": EntityType.DATABASE,
        "aliases": ["Milvus", "milvus"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "rag",
        "display_name": "Retrieval-Augmented Generation",
        "type": EntityType.CONCEPT,
        "aliases": ["RAG", "Retrieval-Augmented Generation", "Retrieval Augmented Generation", "Hybrid RAG"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "llm",
        "display_name": "Large Language Models",
        "type": EntityType.CONCEPT,
        "aliases": ["LLM", "LLMs", "Large Language Model", "Large Language Models"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "prompt-engineering",
        "display_name": "Prompt Engineering",
        "type": EntityType.CONCEPT,
        "aliases": ["Prompt Engineering", "Prompt Optimization"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "agentic-ai",
        "display_name": "Agentic AI",
        "type": EntityType.CONCEPT,
        "aliases": ["Agentic AI", "AI Agents", "Autonomous Agents"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "gnn",
        "display_name": "Graph Neural Networks",
        "type": EntityType.CONCEPT,
        "aliases": ["GNN", "GNNs", "Graph Neural Network", "Graph Neural Networks", "Graph ML"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "gcn",
        "display_name": "Graph Convolutional Network",
        "type": EntityType.CONCEPT,
        "aliases": ["GCN", "Graph Convolutional Network", "Graph Convolutional Networks"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "cnn",
        "display_name": "Convolutional Neural Network",
        "type": EntityType.CONCEPT,
        "aliases": ["CNN", "CNNs", "Convolutional Neural Network", "Convolutional Neural Networks"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "bert",
        "display_name": "BERT",
        "type": EntityType.CONCEPT,
        "aliases": ["BERT", "RoBERTa", "DeBERTa"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "shap",
        "display_name": "SHAP",
        "type": EntityType.LIBRARY,
        "aliases": ["SHAP", "SHAP Explainability", "Shapley Additive Explanations"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "apache-spark",
        "display_name": "Apache Spark",
        "type": EntityType.FRAMEWORK,
        "aliases": ["Apache Spark", "Spark", "PySpark", "Spark SQL", "Spark Streaming"],
        "ambiguous": True,
        "disambiguation_rules": [
            DisambiguationRule(
                case_sensitive=True,
                requires_context=True,
                context_keywords=["data", "distributed", "big data", "hadoop", "streaming", "cluster", "pyspark", "etl", "analytics", "scala", "python", "sql", "databricks"],
                trigger_patterns=[
                    r"\bApache\s+Spark\b",
                    r"\bPySpark\b",
                    r"\bSpark\s+(cluster|job|jobs|streaming|sql|dataframe|dataframes|pipeline)\b",
                    r"\b(Hadoop|Kafka|Flink)\s*[,/]\s*Spark\b",
                    r"\bSpark\s*[,/]\s*(Hadoop|Kafka|Flink)\b",
                ],
                negative_patterns=[r"\b(spark\s+of|sparked|sparking|bright\s+spark)\b"],
            )
        ],
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },

    # ----------------------------------------------------
    # 4. Databases & Storage (Source: Stack Overflow, CC BY-SA 4.0)
    # ----------------------------------------------------
    {
        "canonical_id": "postgresql",
        "display_name": "PostgreSQL",
        "type": EntityType.DATABASE,
        "aliases": ["PostgreSQL", "Postgres", "psql", "Postgre-SQL"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "mysql",
        "display_name": "MySQL",
        "type": EntityType.DATABASE,
        "aliases": ["MySQL", "mysql"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "sqlite",
        "display_name": "SQLite",
        "type": EntityType.DATABASE,
        "aliases": ["SQLite", "sqlite", "sqlite3"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "mongodb",
        "display_name": "MongoDB",
        "type": EntityType.DATABASE,
        "aliases": ["MongoDB", "Mongo", "mongo"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "redis",
        "display_name": "Redis",
        "type": EntityType.DATABASE,
        "aliases": ["Redis", "redis"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "cassandra",
        "display_name": "Apache Cassandra",
        "type": EntityType.DATABASE,
        "aliases": ["Cassandra", "Apache Cassandra"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "elasticsearch",
        "display_name": "Elasticsearch",
        "type": EntityType.DATABASE,
        "aliases": ["Elasticsearch", "ElasticSearch", "ES"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "opensearch",
        "display_name": "OpenSearch",
        "type": EntityType.DATABASE,
        "aliases": ["OpenSearch"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "neo4j",
        "display_name": "Neo4j",
        "type": EntityType.DATABASE,
        "aliases": ["Neo4j", "neo4j", "Cypher"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "dynamodb",
        "display_name": "Amazon DynamoDB",
        "type": EntityType.DATABASE,
        "aliases": ["DynamoDB", "Amazon DynamoDB"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "bigquery",
        "display_name": "Google BigQuery",
        "type": EntityType.DATABASE,
        "aliases": ["BigQuery", "Google BigQuery"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "snowflake",
        "display_name": "Snowflake",
        "type": EntityType.DATABASE,
        "aliases": ["Snowflake", "Snowflake DB"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "clickhouse",
        "display_name": "ClickHouse",
        "type": EntityType.DATABASE,
        "aliases": ["ClickHouse", "clickhouse"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "cockroachdb",
        "display_name": "CockroachDB",
        "type": EntityType.DATABASE,
        "aliases": ["CockroachDB", "Cockroach"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "mariadb",
        "display_name": "MariaDB",
        "type": EntityType.DATABASE,
        "aliases": ["MariaDB", "mariadb"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "oracle-db",
        "display_name": "Oracle Database",
        "type": EntityType.DATABASE,
        "aliases": ["Oracle Database", "Oracle DB", "PL/SQL"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "mssql",
        "display_name": "Microsoft SQL Server",
        "type": EntityType.DATABASE,
        "aliases": ["SQL Server", "MSSQL", "T-SQL", "Microsoft SQL Server"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "supabase",
        "display_name": "Supabase",
        "type": EntityType.DATABASE,
        "aliases": ["Supabase"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "firebase",
        "display_name": "Firebase",
        "type": EntityType.DATABASE,
        "aliases": ["Firebase", "Firestore", "Firebase Realtime Database"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "couchbase",
        "display_name": "Couchbase",
        "type": EntityType.DATABASE,
        "aliases": ["Couchbase", "CouchDB"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "memcached",
        "display_name": "Memcached",
        "type": EntityType.DATABASE,
        "aliases": ["Memcached"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "celery",
        "display_name": "Celery",
        "type": EntityType.TOOL,
        "aliases": ["Celery", "celery", "Celery Task Queue"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "rabbitmq",
        "display_name": "RabbitMQ",
        "type": EntityType.TOOL,
        "aliases": ["RabbitMQ", "rabbitmq", "AMQP"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "apache-kafka",
        "display_name": "Apache Kafka",
        "type": EntityType.TOOL,
        "aliases": ["Apache Kafka", "Kafka", "kafka"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },

    # ----------------------------------------------------
    # 5. Cloud Platforms & Managed Services (Source: Official Providers & Stack Overflow)
    # ----------------------------------------------------
    {
        "canonical_id": "aws",
        "display_name": "Amazon Web Services",
        "type": EntityType.CLOUD,
        "aliases": ["AWS", "Amazon Web Services", "aws"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "aws-lambda",
        "display_name": "AWS Lambda",
        "type": EntityType.CLOUD,
        "aliases": ["AWS Lambda", "Lambda", "Serverless Lambda"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "aws-s3",
        "display_name": "Amazon S3",
        "type": EntityType.CLOUD,
        "aliases": ["Amazon S3", "AWS S3", "S3", "S3 Bucket", "S3 Buckets"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "aws-ec2",
        "display_name": "Amazon EC2",
        "type": EntityType.CLOUD,
        "aliases": ["Amazon EC2", "AWS EC2", "EC2"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "aws-rds",
        "display_name": "Amazon RDS",
        "type": EntityType.CLOUD,
        "aliases": ["Amazon RDS", "AWS RDS", "RDS"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "aws-sqs",
        "display_name": "Amazon SQS",
        "type": EntityType.CLOUD,
        "aliases": ["Amazon SQS", "AWS SQS", "SQS"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "aws-sns",
        "display_name": "Amazon SNS",
        "type": EntityType.CLOUD,
        "aliases": ["Amazon SNS", "AWS SNS", "SNS"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "gcp",
        "display_name": "Google Cloud Platform",
        "type": EntityType.CLOUD,
        "aliases": ["Google Cloud Platform", "GCP", "Google Cloud", "gcp"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "google-cloud-storage",
        "display_name": "Google Cloud Storage",
        "type": EntityType.CLOUD,
        "aliases": ["Google Cloud Storage", "GCS"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "azure",
        "display_name": "Microsoft Azure",
        "type": EntityType.CLOUD,
        "aliases": ["Microsoft Azure", "Azure", "azure"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "azure-functions",
        "display_name": "Azure Functions",
        "type": EntityType.CLOUD,
        "aliases": ["Azure Functions"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "cloudflare",
        "display_name": "Cloudflare",
        "type": EntityType.CLOUD,
        "aliases": ["Cloudflare", "Cloudflare Workers"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "vercel",
        "display_name": "Vercel",
        "type": EntityType.CLOUD,
        "aliases": ["Vercel"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "netlify",
        "display_name": "Netlify",
        "type": EntityType.CLOUD,
        "aliases": ["Netlify"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "heroku",
        "display_name": "Heroku",
        "type": EntityType.CLOUD,
        "aliases": ["Heroku"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "digitalocean",
        "display_name": "DigitalOcean",
        "type": EntityType.CLOUD,
        "aliases": ["DigitalOcean", "Digital Ocean"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "terraform",
        "display_name": "Terraform",
        "type": EntityType.TOOL,
        "aliases": ["Terraform", "terraform", "HCL"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "ansible",
        "display_name": "Ansible",
        "type": EntityType.TOOL,
        "aliases": ["Ansible", "ansible"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "puppet",
        "display_name": "Puppet",
        "type": EntityType.TOOL,
        "aliases": ["Puppet"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "chef",
        "display_name": "Chef",
        "type": EntityType.TOOL,
        "aliases": ["Chef", "Chef Infra"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "pulumi",
        "display_name": "Pulumi",
        "type": EntityType.TOOL,
        "aliases": ["Pulumi"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },

    # ----------------------------------------------------
    # 6. DevOps, Containers & Systems (Source: Stack Overflow, CC BY-SA 4.0)
    # ----------------------------------------------------
    {
        "canonical_id": "docker",
        "display_name": "Docker",
        "type": EntityType.DEVOPS,
        "aliases": ["Docker", "docker", "Dockerfile"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "docker-compose",
        "display_name": "Docker Compose",
        "type": EntityType.DEVOPS,
        "aliases": ["Docker Compose", "docker-compose"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "kubernetes",
        "display_name": "Kubernetes",
        "type": EntityType.DEVOPS,
        "aliases": ["Kubernetes", "K8s", "k8s"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "helm",
        "display_name": "Helm",
        "type": EntityType.DEVOPS,
        "aliases": ["Helm", "Helm Charts"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "git",
        "display_name": "Git",
        "type": EntityType.TOOL,
        "aliases": ["Git", "git"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "github-actions",
        "display_name": "GitHub Actions",
        "type": EntityType.DEVOPS,
        "aliases": ["GitHub Actions", "Github Actions", "GHA"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "gitlab-ci",
        "display_name": "GitLab CI",
        "type": EntityType.DEVOPS,
        "aliases": ["GitLab CI", "Gitlab CI", "GitLab CI/CD"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "jenkins",
        "display_name": "Jenkins",
        "type": EntityType.DEVOPS,
        "aliases": ["Jenkins", "jenkins"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "circleci",
        "display_name": "CircleCI",
        "type": EntityType.DEVOPS,
        "aliases": ["CircleCI", "Circle CI"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "argo-cd",
        "display_name": "Argo CD",
        "type": EntityType.DEVOPS,
        "aliases": ["Argo CD", "ArgoCD"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "prometheus",
        "display_name": "Prometheus",
        "type": EntityType.TOOL,
        "aliases": ["Prometheus", "PromQL"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "grafana",
        "display_name": "Grafana",
        "type": EntityType.TOOL,
        "aliases": ["Grafana", "grafana"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "datadog",
        "display_name": "Datadog",
        "type": EntityType.TOOL,
        "aliases": ["Datadog"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "splunk",
        "display_name": "Splunk",
        "type": EntityType.TOOL,
        "aliases": ["Splunk"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "elk-stack",
        "display_name": "ELK Stack",
        "type": EntityType.TOOL,
        "aliases": ["ELK Stack", "ELK", "Logstash", "Kibana"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "nginx",
        "display_name": "NGINX",
        "type": EntityType.TOOL,
        "aliases": ["NGINX", "Nginx", "nginx"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "apache-httpd",
        "display_name": "Apache HTTP Server",
        "type": EntityType.TOOL,
        "aliases": ["Apache HTTP Server", "Apache Web Server", "httpd"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "caddy",
        "display_name": "Caddy",
        "type": EntityType.TOOL,
        "aliases": ["Caddy", "Caddy Server"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "envoy",
        "display_name": "Envoy",
        "type": EntityType.TOOL,
        "aliases": ["Envoy", "Envoy Proxy"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "istio",
        "display_name": "Istio",
        "type": EntityType.TOOL,
        "aliases": ["Istio", "Service Mesh"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "linux",
        "display_name": "Linux",
        "type": EntityType.PLATFORM,
        "aliases": ["Linux", "Ubuntu", "Debian", "CentOS", "RHEL", "RedHat", "Alpine Linux"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "posix",
        "display_name": "POSIX",
        "type": EntityType.CONCEPT,
        "aliases": ["POSIX", "Linux/POSIX", "Unix", "UNIX"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "ssh",
        "display_name": "SSH",
        "type": EntityType.TOOL,
        "aliases": ["SSH", "OpenSSH"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },

    # ----------------------------------------------------
    # 7. Testing, Build & Quality Tools (Source: Stack Overflow, CC BY-SA 4.0)
    # ----------------------------------------------------
    {
        "canonical_id": "pytest",
        "display_name": "Pytest",
        "type": EntityType.TOOL,
        "aliases": ["Pytest", "pytest"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "unittest",
        "display_name": "Unittest",
        "type": EntityType.TOOL,
        "aliases": ["Unittest", "unittest"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "vitest",
        "display_name": "Vitest",
        "type": EntityType.TOOL,
        "aliases": ["Vitest", "vitest"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "jest",
        "display_name": "Jest",
        "type": EntityType.TOOL,
        "aliases": ["Jest", "jest"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "mocha",
        "display_name": "Mocha",
        "type": EntityType.TOOL,
        "aliases": ["Mocha", "mocha"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "cypress",
        "display_name": "Cypress",
        "type": EntityType.TOOL,
        "aliases": ["Cypress", "cypress"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "playwright",
        "display_name": "Playwright",
        "type": EntityType.TOOL,
        "aliases": ["Playwright", "playwright"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "selenium",
        "display_name": "Selenium",
        "type": EntityType.TOOL,
        "aliases": ["Selenium", "Selenium WebDriver"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "postman",
        "display_name": "Postman",
        "type": EntityType.TOOL,
        "aliases": ["Postman"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "sonarqube",
        "display_name": "SonarQube",
        "type": EntityType.TOOL,
        "aliases": ["SonarQube", "Sonar"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "eslint",
        "display_name": "ESLint",
        "type": EntityType.TOOL,
        "aliases": ["ESLint", "eslint"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "prettier",
        "display_name": "Prettier",
        "type": EntityType.TOOL,
        "aliases": ["Prettier"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "ruff",
        "display_name": "Ruff",
        "type": EntityType.TOOL,
        "aliases": ["Ruff", "ruff"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "mypy",
        "display_name": "Mypy",
        "type": EntityType.TOOL,
        "aliases": ["Mypy", "mypy"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "webpack",
        "display_name": "Webpack",
        "type": EntityType.TOOL,
        "aliases": ["Webpack", "webpack"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "vite",
        "display_name": "Vite",
        "type": EntityType.TOOL,
        "aliases": ["Vite", "vite"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "turborepo",
        "display_name": "Turborepo",
        "type": EntityType.TOOL,
        "aliases": ["Turborepo", "Turbo"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "babel",
        "display_name": "Babel",
        "type": EntityType.TOOL,
        "aliases": ["Babel", "BabelJS"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "gradle",
        "display_name": "Gradle",
        "type": EntityType.TOOL,
        "aliases": ["Gradle"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },
    {
        "canonical_id": "maven",
        "display_name": "Apache Maven",
        "type": EntityType.TOOL,
        "aliases": ["Maven", "Apache Maven", "mvn"],
        "ambiguous": False,
        "source": "stack_overflow",
        "license": "CC-BY-SA-4.0",
    },

    # ----------------------------------------------------
    # 8. Architecture, Concepts & Methodologies (Source: Standard Engineering Curricula & Official Specs)
    # ----------------------------------------------------
    {
        "canonical_id": "oop",
        "display_name": "Object-Oriented Programming",
        "type": EntityType.CONCEPT,
        "aliases": ["OOP", "Object-Oriented Programming", "Object Oriented Programming"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "ood",
        "display_name": "Object-Oriented Design",
        "type": EntityType.CONCEPT,
        "aliases": ["OOD", "Object-Oriented Design", "Object Oriented Design"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "solid",
        "display_name": "SOLID Principles",
        "type": EntityType.CONCEPT,
        "aliases": ["SOLID", "SOLID principles"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "tdd",
        "display_name": "Test-Driven Development",
        "type": EntityType.METHODOLOGY,
        "aliases": ["TDD", "Test-Driven Development", "Test Driven Development"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "bdd",
        "display_name": "Behavior-Driven Development",
        "type": EntityType.METHODOLOGY,
        "aliases": ["BDD", "Behavior-Driven Development", "Behavior Driven Development"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "ci-cd",
        "display_name": "CI/CD",
        "type": EntityType.METHODOLOGY,
        "aliases": ["CI/CD", "CI / CD", "CI-CD", "Continuous Integration", "Continuous Delivery", "Continuous Deployment", "CI/CD Pipelines"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "microservices",
        "display_name": "Microservices",
        "type": EntityType.CONCEPT,
        "aliases": ["Microservices", "Microservices Architecture", "Micro-services", "Microservice", "microservice"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "distributed-systems",
        "display_name": "Distributed Systems",
        "type": EntityType.CONCEPT,
        "aliases": ["Distributed Systems", "Distributed Computing"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "event-driven-architecture",
        "display_name": "Event-Driven Architecture",
        "type": EntityType.CONCEPT,
        "aliases": ["Event-Driven Architecture", "Event Driven Architecture", "EDA"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "agile",
        "display_name": "Agile",
        "type": EntityType.METHODOLOGY,
        "aliases": ["Agile", "Agile Methodology", "Agile Development"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "scrum",
        "display_name": "Scrum",
        "type": EntityType.METHODOLOGY,
        "aliases": ["Scrum", "Scrum Master", "Daily Standup"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "kanban",
        "display_name": "Kanban",
        "type": EntityType.METHODOLOGY,
        "aliases": ["Kanban", "Kanban Board"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "jira",
        "display_name": "Jira",
        "type": EntityType.TOOL,
        "aliases": ["Jira", "Atlassian Jira"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "confluence",
        "display_name": "Confluence",
        "type": EntityType.TOOL,
        "aliases": ["Confluence", "Atlassian Confluence"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "data-structures",
        "display_name": "Data Structures",
        "type": EntityType.CONCEPT,
        "aliases": ["Data Structures", "Data Structures & Algorithms", "DSA"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "algorithms",
        "display_name": "Algorithms",
        "type": EntityType.CONCEPT,
        "aliases": ["Algorithms", "Algorithm Design", "Algorithm", "algorithm", "algorithmic"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "system-design",
        "display_name": "System Design",
        "type": EntityType.CONCEPT,
        "aliases": ["System Design", "High-Level Design", "Low-Level Design", "HLD", "LLD"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "concurrency",
        "display_name": "Concurrency",
        "type": EntityType.CONCEPT,
        "aliases": ["Concurrency", "Concurrent Programming", "Async/Await", "Asynchronous Programming"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "multithreading",
        "display_name": "Multithreading",
        "type": EntityType.CONCEPT,
        "aliases": ["Multithreading", "Multi-threading", "Thread Safety"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "raft-consensus",
        "display_name": "Raft Consensus",
        "type": EntityType.CONCEPT,
        "aliases": ["Raft", "Raft Consensus", "Raft algorithm"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "relational-schema-design",
        "display_name": "Relational Schema Design",
        "type": EntityType.CONCEPT,
        "aliases": ["Relational Schema Design", "Database Normalization", "ER Modeling", "Schema Design"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "physics-engine",
        "display_name": "Physics Engine",
        "type": EntityType.CONCEPT,
        "aliases": ["Physics Engine", "2D Physics", "3D Physics", "Rigid Body Dynamics"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
    {
        "canonical_id": "systems-simulation",
        "display_name": "Systems Simulation",
        "type": EntityType.CONCEPT,
        "aliases": ["Systems Simulation", "System Simulation", "Neural Simulation", "Numerical Simulation"],
        "ambiguous": False,
        "source": "official_project_spec",
        "license": "permissive_open_source",
    },
]

PROVENANCE_MANIFEST = {
    "version": "1.0.0",
    "generation_date": "2026-10-04",
    "sources": [
        {
            "name": "github_linguist",
            "url": "https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml",
            "license": "MIT",
            "description": "GitHub Linguist programming language specifications and aliases.",
            "terms": "Permissive MIT license allows modification, redistribution, and commercial use.",
        },
        {
            "name": "stack_overflow",
            "url": "https://data.stackexchange.com/stackoverflow/query/new",
            "license": "CC-BY-SA-4.0",
            "description": "Stack Overflow Tag Synonyms and canonical technology terms.",
            "terms": "Creative Commons Attribution-ShareAlike 4.0 International allows redistribution with attribution.",
        },
        {
            "name": "official_project_spec",
            "url": "https://careercompiler.local/specs/taxonomy",
            "license": "permissive_open_source",
            "description": "Standard software architecture patterns, cloud services, and candidate project technologies.",
            "terms": "Permissive documentation and public specifications.",
        },
    ],
}


def generate() -> None:
    data_dir = Path("careercompiler/taxonomy/data")
    data_dir.mkdir(parents=True, exist_ok=True)

    entities: list[TaxonomyEntity] = []
    for item in ENTITIES_DATA:
        e = TaxonomyEntity(
            canonical_id=item["canonical_id"],
            display_name=item["display_name"],
            type=item["type"],
            aliases=item["aliases"],
            ambiguous=item.get("ambiguous", False),
            disambiguation_rules=item.get("disambiguation_rules", []),
            source=item["source"],
            license=item["license"],
            version="1.0.0",
            reviewed=True,
        )
        entities.append(e)

    catalog = TaxonomyCatalog(entities=entities)

    # Count breakdown
    by_source: dict[str, int] = {}
    by_type: dict[str, int] = {}
    by_license: dict[str, int] = {}
    unreviewed = sum(1 for e in catalog.entities if not e.reviewed)

    for e in catalog.entities:
        by_source[e.source] = by_source.get(e.source, 0) + 1
        by_type[e.type.value] = by_type.get(e.type.value, 0) + 1
        by_license[e.license] = by_license.get(e.license, 0) + 1

    print(f"Total entities: {len(catalog.entities)}")
    print(f"Unreviewed count: {unreviewed}")
    print(f"Entities by source: {by_source}")
    print(f"Entities by type: {by_type}")
    print(f"Entities by license: {by_license}")

    # Save seed taxonomy JSON
    seed_path = data_dir / "seed_taxonomy.json"
    with open(seed_path, "w", encoding="utf-8") as f:
        json.dump([e.model_dump() for e in catalog.entities], f, indent=2)
    print(f"Wrote seed taxonomy to {seed_path}")

    # Save provenance manifest
    manifest_data = dict(PROVENANCE_MANIFEST)
    manifest_data["summary"] = {
        "total_entities": len(catalog.entities),
        "unreviewed_count": unreviewed,
        "by_source": by_source,
        "by_type": by_type,
        "by_license": by_license,
    }
    manifest_path = data_dir / "provenance_manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest_data, f, indent=2)
    print(f"Wrote provenance manifest to {manifest_path}")


if __name__ == "__main__":
    generate()
